#want the total number of different RNA strings from which the protein
#could have been translated, modulo 1,000,000
#sample output = 12 (aka # dif RNA strings/1,000,000 gives 12 as remainder??)
#could have been: 1) AUG - GCU - UAA, 2) AUG - GCU - UAG, 3) AUG - GCU, UGA,
#4) AUG - GCC - UAA, 5) AUG - GCC - UAG, 6) AUG - GCC, UGA,
#7) AUG - GCA - UAA, 8) AUG - GCA - UAG, 9) AUG - GCA, UGA,
#10) AUG - GCG - UAA, 11) AUG - GCG - UAG, 12) AUG - GCG - UGA
# 1 (# codons that translate to m) x 4 (# codons that translate to A) x 3 (# codons that translate to stop) = 12
#want to %1000000 at the end 
#Stop = 3 #will always need to be multiplied by 3


number_strings = {'F':2,'L':6,'S':6,'Y':2,'C':2,'W':1,'P':4,'H':2,'Q':2,'R':6,'I':3,'M':1,'T':4,'N':2,'K':2,'V':4,'A':4,'D':2,'E':2,'G':4}
s = 'MTLRCPRFHPTFQHIPFMMWQEAGMNIKWYCQEEGGQKHDHTQIGVNWARIYNLMYQFNKTLEEPKSIAWMTQMCVMARIHQHPTDDDWRIILWKIWDPMEMLAKLIPFEYQTSMHIYWYRLNLSGWDSNIRLPFNDEPMVNREFFVQPNHSMGRWWSKYAETFFINFDQWANTSEHNQPQLMMSHHMAFQWNPMYTAENEWMGCGDPHEDQGGFKEQMQEDPFIWYYYSYFELMSRVWCHLVVLACFMPMMQMGQVGRYGKEQACQCCEDIAPHFCYNKLDNCKEYISEDNRWSAGYSRAGKHFLCHKKNACNHQNCNPDNDWIFIRRCMIWIRCTTQTYLYRKPSRPGSCEMHEWVVFWFRYQFIFRERASEEEAMSDFPAVWNVSHQDRRINEFDHDWHNEWMHGQVDVEFFWWVTLCFTEIHDNCEFCKAFQHAHKTQFHCMIRTDLDCQPFGHRALGWNLPIWIYPEHDGMGSIQNRAMYEEAATVGLYLGRCNKHSIHWHYCTFAASSLRHLTTWWRIGIPASNEVFVIWIQCHMKHIFAAQMMFYVPIYCSLHPMPYLERCFAMLSEDAKSCMGVMSRSIFSTAIKRFKEGGMYQYKCHTCMTNDVNAFMYRHALPLCHWKCAWHPIISYMADVIGAFGDDCLYSPNAPDYENSEQEDREPQQLYGLKARCAFNTGQNWWQHYRMTFTDFMINLLDITHGSWQISTHANHAVYFFDSEIDQMSCMMHCYQQNMTWLMNYFAKLSELNLCWMHEVRTKVRIQTAKGLMNHMENCMPCLTDGRSKEFLRDYGFSTNTRPPKNAHEPMKADWMRFQYIVTSGRKFEIHMICLFDNWSFRWINMRTGENDIPLQANSMKPRESGRMHTQITVIYVYAYHKFELMHRDRKNFELSPIYDADQQKAHWYYAKWDKGRTRENSCGIGVFWTLFFINHPGYCQHMPAETIMRSFKKGKPFEVKGWTKTHPQMNHMKSATMYPHRGEVTPRFRTQEHHE'



def extract_number_dif_strings(protein_string, dictionary):
    number_strings = []
    for i in protein_string:
        number_strings.append(dictionary[i])
    return number_strings

def number_RNA_strings(protein_string, dictionary):
    Output = 3
    for i in extract_number_dif_strings(protein_string, dictionary):
        Output *= i
    return Output%1000000

print(number_RNA_strings(s, number_strings))


